### ISSUE TITLE
Text area :  Empty line bug

### ISSUE THREAD

**Issue by ahmedhem** [ahmedhem/AlgoGraph#13]
Empty lines are treated as edges.
fix : ignore empty lines.

**Comment by ahmedEid1** [comment]
Fixed in commit https://github.com/ahmedhem/AlgoGraph/commit/d62a6abc0e380c2db3ed73cdd2c4b14892da6f5a
by filter the lines from any line with length 0
```js
  lines = lines.filter(line => line.length > 0)

```
